-- ============================================================================
-- SmartBudget: full database setup in one paste (Supabase SQL editor).
-- Generated by tool/build_supabase_setup.sh from, in this order:
--   schema.sql cloud_backup.sql billing.sql coupons.sql ai_gateway.sql ai_reports.sql receipt_scanner.sql security_hardening.sql
-- Edit those files, not this one. Runs as one transaction (all or
-- nothing) and is safe to run again.
-- ============================================================================

begin;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> schema.sql

-- ============================================================================
-- SmartBudget — by DGOTIX · Database foundation (Supabase / PostgreSQL)
-- ----------------------------------------------------------------------------
-- Design notes:
--  • Money is stored as BIGINT MINOR UNITS (e.g. cents) + a currency code, to
--    avoid floating-point error in financial math. Never store money as float.
--  • Every user-owned table carries user_id and is protected by Row-Level
--    Security so a user can only ever read/write their own rows (real data
--    isolation, enforced by the database, not the client).
--  • This mirrors the existing SmartBudget domain (income/expense, goals,
--    debts, zakat, financial health). It does NOT change any financial rule —
--    calculators re-implement V1 logic in the app/service layer.
--
-- Apply with the Supabase SQL editor or CLI migrations. Idempotent-ish: uses
-- IF NOT EXISTS where practical. Review before running in production.
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Reference data (global, read-only to clients)
-- ---------------------------------------------------------------------------
create table if not exists currencies (
  code        text primary key,             -- e.g. 'USD', 'DZD'
  name_ar     text not null,
  name_en     text not null,
  symbol      text not null,
  decimals    smallint not null default 2
);

create table if not exists exchange_rates (
  id          uuid primary key default gen_random_uuid(),
  code        text not null references currencies(code),
  rate_vs_usd numeric(18,6) not null,        -- units of `code` per 1 USD
  fetched_at  timestamptz not null default now()
);
create index if not exists idx_rates_code_time on exchange_rates(code, fetched_at desc);

-- Every currency the app offers (lib/core/money/currency.dart). profiles
-- .base_currency references this table, so it must be filled before the
-- first sign-up or creating the profile row fails.
insert into currencies (code, name_ar, name_en, symbol, decimals) values
  ('USD', 'الدولار الأمريكي', 'US Dollar', '$', 2),
  ('DZD', 'الدينار الجزائري', 'Algerian Dinar', 'د.ج', 2),
  ('SAR', 'الريال السعودي', 'Saudi Riyal', 'ر.س', 2),
  ('AED', 'الدرهم الإماراتي', 'UAE Dirham', 'د.إ', 2),
  ('QAR', 'الريال القطري', 'Qatari Riyal', 'ر.ق', 2),
  ('KWD', 'الدينار الكويتي', 'Kuwaiti Dinar', 'د.ك', 3),
  ('BHD', 'الدينار البحريني', 'Bahraini Dinar', 'د.ب', 3),
  ('OMR', 'الريال العماني', 'Omani Rial', 'ر.ع', 3),
  ('JOD', 'الدينار الأردني', 'Jordanian Dinar', 'د.أ', 3),
  ('EGP', 'الجنيه المصري', 'Egyptian Pound', 'ج.م', 2),
  ('MAD', 'الدرهم المغربي', 'Moroccan Dirham', 'د.م', 2),
  ('TND', 'الدينار التونسي', 'Tunisian Dinar', 'د.ت', 3),
  ('LYD', 'الدينار الليبي', 'Libyan Dinar', 'د.ل', 3),
  ('IQD', 'الدينار العراقي', 'Iraqi Dinar', 'د.ع', 3),
  ('LBP', 'الليرة اللبنانية', 'Lebanese Pound', 'ل.ل', 2),
  ('SYP', 'الليرة السورية', 'Syrian Pound', 'ل.س', 2),
  ('SDG', 'الجنيه السوداني', 'Sudanese Pound', 'ج.س', 2),
  ('YER', 'الريال اليمني', 'Yemeni Rial', 'ر.ي', 2),
  ('MRU', 'الأوقية الموريتانية', 'Mauritanian Ouguiya', 'أ.م', 2),
  ('EUR', 'اليورو', 'Euro', '€', 2),
  ('GBP', 'الجنيه الإسترليني', 'Pound Sterling', '£', 2),
  ('JPY', 'الين الياباني', 'Japanese Yen', '¥', 0),
  ('CNY', 'اليوان الصيني', 'Chinese Yuan', '¥', 2),
  ('CHF', 'الفرنك السويسري', 'Swiss Franc', 'Fr', 2),
  ('CAD', 'الدولار الكندي', 'Canadian Dollar', 'C$', 2),
  ('AUD', 'الدولار الأسترالي', 'Australian Dollar', 'A$', 2),
  ('INR', 'الروبية الهندية', 'Indian Rupee', '₹', 2),
  ('TRY', 'الليرة التركية', 'Turkish Lira', '₺', 2),
  ('RUB', 'الروبل الروسي', 'Russian Ruble', '₽', 2),
  ('BRL', 'الريال البرازيلي', 'Brazilian Real', 'R$', 2),
  ('ZAR', 'الراند الجنوب إفريقي', 'South African Rand', 'R', 2),
  ('SGD', 'الدولار السنغافوري', 'Singapore Dollar', 'S$', 2),
  ('KRW', 'الوون الكوري الجنوبي', 'South Korean Won', '₩', 0),
  ('SEK', 'الكرونة السويدية', 'Swedish Krona', 'kr', 2),
  ('MXN', 'البيزو المكسيكي', 'Mexican Peso', 'Mex$', 2)
on conflict (code) do update set
  name_ar = excluded.name_ar, name_en = excluded.name_en,
  symbol = excluded.symbol, decimals = excluded.decimals;

-- ---------------------------------------------------------------------------
-- Profiles (1:1 with auth.users)
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  display_name  text,
  locale        text not null default 'ar',
  theme         text not null default 'dark',
  base_currency text not null default 'USD' references currencies(code),
  plan          text not null default 'free',   -- free | basic | pro | ultimate
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- User taxonomy
-- ---------------------------------------------------------------------------
create table if not exists categories (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  kind        text not null check (kind in ('income','expense')),
  name        text not null,
  is_default  boolean not null default false,
  created_at  timestamptz not null default now()
);
create index if not exists idx_categories_user on categories(user_id);

create table if not exists payment_methods (
  id       uuid primary key default gen_random_uuid(),
  user_id  uuid not null references auth.users(id) on delete cascade,
  name     text not null
);
create index if not exists idx_payment_methods_user on payment_methods(user_id);

-- ---------------------------------------------------------------------------
-- Transactions (unified income/expense ledger)
-- ---------------------------------------------------------------------------
create table if not exists transactions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  txn_date      date not null,
  type          text not null check (type in ('income','expense')),
  category_id   uuid references categories(id) on delete set null,
  description   text,
  amount_minor  bigint not null check (amount_minor >= 0),
  currency      text not null references currencies(code),
  payment_method_id uuid references payment_methods(id) on delete set null,
  notes         text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_txn_user_date on transactions(user_id, txn_date desc);
create index if not exists idx_txn_user_type on transactions(user_id, type);

-- ---------------------------------------------------------------------------
-- Monthly budgets (planned amounts per category)
-- ---------------------------------------------------------------------------
create table if not exists budgets (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  year          smallint not null,
  month         smallint not null check (month between 1 and 12),
  category_id   uuid references categories(id) on delete set null,
  planned_minor bigint not null default 0,
  unique (user_id, year, month, category_id)
);
create index if not exists idx_budgets_user on budgets(user_id, year, month);

-- ---------------------------------------------------------------------------
-- Goals & savings
-- ---------------------------------------------------------------------------
create table if not exists goals (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  name          text not null,
  target_minor  bigint not null check (target_minor >= 0),
  currency      text not null references currencies(code),
  deadline      date,
  created_at    timestamptz not null default now()
);
create index if not exists idx_goals_user on goals(user_id);

-- Saved amount is DERIVED from allocations (never a hardcoded seed) — matches
-- V1's recalcGoalSavings behavior.
create table if not exists goal_allocations (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  goal_id        uuid not null references goals(id) on delete cascade,
  transaction_id uuid references transactions(id) on delete set null,
  amount_minor   bigint not null,
  alloc_date     date not null default current_date
);
create index if not exists idx_alloc_user_goal on goal_allocations(user_id, goal_id);

-- ---------------------------------------------------------------------------
-- Debts ledger (money lent / borrowed)
-- ---------------------------------------------------------------------------
create table if not exists debts (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  party         text not null,
  type          text not null check (type in ('lent','borrowed')), -- لي / عليّ
  original_minor bigint not null check (original_minor >= 0),
  paid_minor    bigint not null default 0 check (paid_minor >= 0),
  currency      text not null references currencies(code),
  debt_date     date not null default current_date,
  due_date      date,
  notes         text,
  created_at    timestamptz not null default now()
  -- remaining_minor and status are computed in the app/service layer
  -- (remaining = max(0, original - paid); status: active/paid), matching V1.
);
create index if not exists idx_debts_user on debts(user_id);

-- ---------------------------------------------------------------------------
-- Zakat records (historical log, per year)
-- ---------------------------------------------------------------------------
create table if not exists zakat_records (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  year             smallint not null,
  nisab_basis      text not null check (nisab_basis in ('gold','silver')),
  net_zakatable_minor bigint not null default 0,
  nisab_minor      bigint not null default 0,
  due_minor        bigint not null default 0,
  currency         text not null references currencies(code),
  calc_date        timestamptz not null default now(),
  unique (user_id, year)
);

-- ---------------------------------------------------------------------------
-- Financial health snapshots (score + factor breakdown as JSON)
-- ---------------------------------------------------------------------------
create table if not exists financial_health_snapshots (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  period       text not null,             -- e.g. '2026', '2026-Q1'
  score        numeric(5,2) not null,     -- 0..100
  factors      jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);
create index if not exists idx_health_user on financial_health_snapshots(user_id, created_at desc);

-- ============================================================================
-- Row-Level Security
-- ============================================================================
alter table profiles                    enable row level security;
alter table categories                  enable row level security;
alter table payment_methods             enable row level security;
alter table transactions                enable row level security;
alter table budgets                     enable row level security;
alter table goals                       enable row level security;
alter table goal_allocations            enable row level security;
alter table debts                       enable row level security;
alter table zakat_records               enable row level security;
alter table financial_health_snapshots  enable row level security;

-- Reference data: readable by any authenticated user, writable by nobody (via
-- client). Rates are refreshed by a trusted scheduled job using the service role.
alter table currencies     enable row level security;
alter table exchange_rates enable row level security;
drop policy if exists currencies_read on currencies;
create policy currencies_read on currencies
  for select using (auth.role() = 'authenticated');
drop policy if exists exchange_rates_read on exchange_rates;
create policy exchange_rates_read on exchange_rates
  for select using (auth.role() = 'authenticated');

-- Profiles: a user sees/edits only their own profile row.
drop policy if exists profiles_self on profiles;
create policy profiles_self on profiles
  for all using (id = auth.uid()) with check (id = auth.uid());

-- Owned tables: full isolation on user_id. One policy per table (same shape).
do $$
declare t text;
begin
  foreach t in array array[
    'categories','payment_methods','transactions','budgets','goals',
    'goal_allocations','debts','zakat_records','financial_health_snapshots'
  ] loop
    execute format('drop policy if exists %1$s_owner on %1$s;', t);
    execute format(
      'create policy %1$s_owner on %1$s for all
         using (user_id = auth.uid()) with check (user_id = auth.uid());', t);
  end loop;
end $$;

-- Auto-provision a profile row on signup.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', null))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> cloud_backup.sql

-- SmartBudget — Cloud Backup storage (Supabase / Postgres).
--
-- PURPOSE
--   Store one portable backup snapshot per signed-in user so their data can be
--   synced to their account and restored on any device. The snapshot is the
--   same backend-agnostic JSON produced by the app's local backup (BackupData),
--   stored as jsonb.
--
-- SECURITY
--   Row Level Security locks every row to its owner: a user can only read or
--   write the row whose user_id equals their auth.uid(). The anon key + the
--   user's JWT are all the client needs — no service-role key ships to the
--   frontend, and no user can see another user's data.
--
-- APPLY
--   Run this in the Supabase SQL editor (or `supabase db push`) once. The
--   feature stays dormant in the app until SUPABASE_URL/ANON_KEY are configured.

create table if not exists public.user_backups (
  user_id        uuid primary key references auth.users (id) on delete cascade,
  data           jsonb       not null,
  schema_version integer     not null default 1,
  updated_at     timestamptz not null default now()
);

alter table public.user_backups enable row level security;

-- Owner-only access. Each policy re-checks auth.uid() = user_id.
drop policy if exists "own backup - select" on public.user_backups;
create policy "own backup - select"
  on public.user_backups for select
  using (auth.uid() = user_id);

drop policy if exists "own backup - insert" on public.user_backups;
create policy "own backup - insert"
  on public.user_backups for insert
  with check (auth.uid() = user_id);

drop policy if exists "own backup - update" on public.user_backups;
create policy "own backup - update"
  on public.user_backups for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "own backup - delete" on public.user_backups;
create policy "own backup - delete"
  on public.user_backups for delete
  using (auth.uid() = user_id);

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> billing.sql

-- ============================================================================
-- SmartBudget — Billing (subscriptions via a provider, default: Paddle)
-- ----------------------------------------------------------------------------
-- Provider-agnostic: the app never talks to the provider directly. A checkout
-- is created server-side (create-checkout) and the provider's webhook
-- (paddle-webhook) is the ONLY thing that grants/revokes entitlement — the
-- server stays the source of truth. Provider API keys live ONLY in Edge
-- Function secrets, never in the DB or the frontend.
--
-- Apply via the Supabase SQL editor or CLI. Safe to re-run. Requires
-- ai_gateway.sql (for ai_entitlements) to have been applied first.
-- ============================================================================

-- ---- Price map: provider price id -> (plan, period) ----------------------
-- The owner creates products/prices in the provider dashboard, then records the
-- ids here (no app release needed). This is the single mapping both checkout
-- and the webhook use, so a plan can never be granted from an unknown price.
create table if not exists billing_prices (
  price_id   text primary key,          -- provider price id (e.g. Paddle 'pri_...')
  provider   text not null default 'paddle',
  plan       text not null,             -- 'basic' | 'pro'
  period     text not null,             -- 'monthly' | 'yearly'
  active     boolean not null default true,
  updated_at timestamptz not null default now()
);

-- ---- One current subscription per user -----------------------------------
create table if not exists subscriptions (
  user_id                 uuid primary key references auth.users(id) on delete cascade,
  provider                text not null default 'paddle',
  provider_customer_id    text,
  provider_subscription_id text,
  plan                    text not null default 'free',
  period                  text,
  status                  text,          -- active | trialing | past_due | canceled | ...
  current_period_end      timestamptz,
  cancel_at_period_end    boolean not null default false,
  updated_at              timestamptz not null default now()
);

-- ---- Webhook idempotency + audit -----------------------------------------
create table if not exists billing_events (
  event_id    text primary key,          -- provider event id
  provider    text not null default 'paddle',
  type        text,
  received_at timestamptz not null default now()
);

-- ---- RLS ------------------------------------------------------------------
alter table billing_prices  enable row level security;
alter table subscriptions   enable row level security;
alter table billing_events  enable row level security;

-- Price map + events: no client access (service role only).
revoke all on table billing_prices from anon, authenticated;
revoke all on table billing_events from anon, authenticated;

-- A user may read only their own subscription (writes go through service role).
drop policy if exists subscriptions_own on subscriptions;
create policy subscriptions_own on subscriptions
  for select using (auth.uid() = user_id);

-- ---- Example seed (commented; the owner fills real provider ids) ---------
-- Paddle uses price ids (pri_...); PayPal uses billing PLAN ids (P-...). The
-- provider column keeps both sets side by side, so the app can offer either.
-- insert into billing_prices (price_id, provider, plan, period) values
--   ('pri_basic_monthly', 'paddle', 'basic', 'monthly'),
--   ('pri_basic_yearly',  'paddle', 'basic', 'yearly'),
--   ('pri_pro_monthly',   'paddle', 'pro',   'monthly'),
--   ('pri_pro_yearly',    'paddle', 'pro',   'yearly'),
--   ('P-BASIC-MONTHLY',   'paypal', 'basic', 'monthly'),
--   ('P-BASIC-YEARLY',    'paypal', 'basic', 'yearly'),
--   ('P-PRO-MONTHLY',     'paypal', 'pro',   'monthly'),
--   ('P-PRO-YEARLY',      'paypal', 'pro',   'yearly')
-- on conflict (price_id) do nothing;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> coupons.sql

-- ============================================================================
-- SmartBudget — Coupons (marketing discount codes)
-- ----------------------------------------------------------------------------
-- A coupon changes the PRICE of a checkout (or grants a trial); it never itself
-- unlocks a feature — the plan does that (see docs/PRICING.md §7). Validation
-- and redemption are SERVER-SIDE ONLY (the `coupon-validate` Edge Function uses
-- the service role): coupons are NOT world-readable, so codes can't be
-- enumerated or forged from the client.
--
-- Apply via the Supabase SQL editor or CLI. Safe to re-run.
-- ============================================================================

create table if not exists coupons (
  code            text primary key,          -- stored UPPER-CASE; compared case-insensitively
  kind            text not null,             -- 'percent' | 'fixed' | 'trial_extension'
  value           numeric not null,          -- percent (0-100) | USD off | trial days
  target_plan     text,                      -- 'basic' | 'pro' | null (any)
  target_period   text,                      -- 'monthly' | 'yearly' | null (any)
  valid_from      timestamptz,               -- null = no lower bound
  valid_until     timestamptz,               -- null = no upper bound
  max_redemptions int,                       -- null = unlimited (global cap)
  per_user_limit  int not null default 1,    -- redemptions allowed per user
  active          boolean not null default true,
  note            text,                      -- internal description (campaign)
  created_at      timestamptz not null default now()
);

-- One row per successful redemption (written at checkout by the service role).
create table if not exists coupon_redemptions (
  id          bigint generated always as identity primary key,
  code        text not null references coupons(code) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now()
);
create index if not exists coupon_redemptions_code_idx on coupon_redemptions(code);
create index if not exists coupon_redemptions_user_idx on coupon_redemptions(user_id);

-- One row per code checked, so a user can't try codes without limit (the
-- coupon-validate function allows a few per hour). Kept for a day at most.
create table if not exists coupon_attempts (
  id           bigint generated always as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  attempted_at timestamptz not null default now()
);
create index if not exists coupon_attempts_user_idx
  on coupon_attempts(user_id, attempted_at);

-- ---- RLS ------------------------------------------------------------------
alter table coupons            enable row level security;
alter table coupon_redemptions enable row level security;
alter table coupon_attempts    enable row level security;

-- Coupons: NO client access at all (service role bypasses RLS). A user must go
-- through the coupon-validate function, which never leaks the code list.
revoke all on table coupons from anon, authenticated;

-- Attempts: no client access either (only the function counts them).
revoke all on table coupon_attempts from anon, authenticated;

-- Redemptions: a user may read only their own (writes go through service role).
drop policy if exists coupon_redemptions_own on coupon_redemptions;
create policy coupon_redemptions_own on coupon_redemptions
  for select using (auth.uid() = user_id);

-- ---- Example seed (commented; the owner creates real campaigns) -----------
-- insert into coupons (code, kind, value, target_plan, valid_until, max_redemptions, note)
-- values ('LAUNCH25', 'percent', 25, null, now() + interval '30 days', 500, 'Launch 25% off')
-- on conflict (code) do nothing;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ai_gateway.sql

-- ============================================================================
-- SmartBudget — DGOTIX AI Gateway: config, entitlement, usage, observability
-- ----------------------------------------------------------------------------
-- Used by the `ai-gateway` Edge Function. Provider keys are NOT stored here —
-- they live only in Edge Function secrets. These tables let an owner change
-- routing/kill-switches/quotas from the DB with no app release.
--
-- RLS:
--  • ai_provider_flags / ai_model_flags : world-readable (config), writes only
--    via service role or the SQL editor (owner).
--  • ai_entitlements / ai_usage_monthly : a user may READ their own row; only
--    the service role (Edge Function) writes.
--  • ai_request_log : no client access at all (service role only).
--
-- Apply via the Supabase SQL editor or CLI. Safe to re-run.
-- ============================================================================

-- ---- Provider kill switch + priority -------------------------------------
create table if not exists ai_provider_flags (
  provider_id text primary key,           -- 'google' | 'openai' | 'anthropic'
  enabled     boolean not null default true,
  priority    int,                        -- lower = preferred (null = default)
  updated_at  timestamptz not null default now()
);

-- ---- Per-model kill switch + pricing + priority --------------------------
create table if not exists ai_model_flags (
  model_id     text primary key,          -- e.g. 'gemini-flash-latest'
  provider_id  text not null,
  enabled      boolean not null default true,
  input_per_m  numeric,                   -- USD / 1M tokens (null = code default)
  output_per_m numeric,
  priority     int,
  updated_at   timestamptz not null default now()
);

-- ---- Per-user entitlement (plan) -----------------------------------------
-- The PLAN drives the limits (see supabase/functions/_shared/quota.ts, which
-- mirrors the app's FeatureCatalog). The numeric *_limit columns are kept for
-- backward-compat / rare per-user overrides but are NOT the source of truth.
create table if not exists ai_entitlements (
  user_id                uuid primary key references auth.users(id) on delete cascade,
  plan                   text not null default 'free',
  monthly_request_limit  int not null default 50,
  monthly_cost_limit_usd numeric not null default 0.50,
  updated_at             timestamptz not null default now()
);

-- Time-boxed trial: a temporarily granted higher plan that lapses back to the
-- paid plan with no data loss. Added idempotently for existing deployments.
alter table ai_entitlements add column if not exists trial_plan text;
alter table ai_entitlements add column if not exists trial_expires_at timestamptz;

-- ---- Per-user monthly usage (AI counter) ---------------------------------
create table if not exists ai_usage_monthly (
  user_id       uuid not null references auth.users(id) on delete cascade,
  month         text not null,            -- 'YYYY-MM' (UTC)
  requests      int not null default 0,
  input_tokens  bigint not null default 0,
  output_tokens bigint not null default 0,
  est_cost_usd  numeric not null default 0,
  updated_at    timestamptz not null default now(),
  primary key (user_id, month)
);

-- ---- Per-user lifetime usage (AI counter) --------------------------------
-- FREE's AI allowance is a one-time (lifetime) intro, not a monthly refill, so
-- it is enforced against this counter. Bumped on every successful answer.
create table if not exists ai_usage_lifetime (
  user_id  uuid primary key references auth.users(id) on delete cascade,
  requests int not null default 0,
  updated_at timestamptz not null default now()
);

-- ---- Cloud OCR usage counters (monthly + lifetime) -----------------------
-- Cloud receipt OCR is metered per plan (3 / 15 / 100). On-device OCR is NOT
-- metered. These back the ocr enforcement (see quota.ts OCR_QUOTA).
create table if not exists ocr_usage_monthly (
  user_id uuid not null references auth.users(id) on delete cascade,
  month   text not null,                  -- 'YYYY-MM' (UTC)
  scans   int not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, month)
);
create table if not exists ocr_usage_lifetime (
  user_id uuid primary key references auth.users(id) on delete cascade,
  scans   int not null default 0,
  updated_at timestamptz not null default now()
);

-- ---- Observability (no keys, no prompts) ---------------------------------
create table if not exists ai_request_log (
  id            bigint generated always as identity primary key,
  user_id       uuid,
  task          text,
  provider      text,
  model         text,
  fallback_used boolean default false,
  latency_ms    int,
  input_tokens  int,
  output_tokens int,
  est_cost_usd  numeric,
  error_code    text,
  created_at    timestamptz not null default now()
);

-- ---- RLS ------------------------------------------------------------------
alter table ai_provider_flags enable row level security;
alter table ai_model_flags    enable row level security;
alter table ai_entitlements   enable row level security;
alter table ai_usage_monthly  enable row level security;
alter table ai_usage_lifetime enable row level security;
alter table ocr_usage_monthly enable row level security;
alter table ocr_usage_lifetime enable row level security;
alter table ai_request_log    enable row level security;

-- Config is readable by clients (so a diagnostics screen can show it); writes
-- go through the service role / SQL editor only.
drop policy if exists ai_provider_flags_read on ai_provider_flags;
create policy ai_provider_flags_read on ai_provider_flags for select using (true);
drop policy if exists ai_model_flags_read on ai_model_flags;
create policy ai_model_flags_read on ai_model_flags for select using (true);

-- A user may read only their own entitlement + usage counters.
drop policy if exists ai_entitlements_own on ai_entitlements;
create policy ai_entitlements_own on ai_entitlements for select using (auth.uid() = user_id);
drop policy if exists ai_usage_own on ai_usage_monthly;
create policy ai_usage_own on ai_usage_monthly for select using (auth.uid() = user_id);
drop policy if exists ai_usage_life_own on ai_usage_lifetime;
create policy ai_usage_life_own on ai_usage_lifetime for select using (auth.uid() = user_id);
drop policy if exists ocr_usage_own on ocr_usage_monthly;
create policy ocr_usage_own on ocr_usage_monthly for select using (auth.uid() = user_id);
drop policy if exists ocr_usage_life_own on ocr_usage_lifetime;
create policy ocr_usage_life_own on ocr_usage_lifetime for select using (auth.uid() = user_id);

-- Logs: no client access (service role bypasses RLS). Defense in depth.
revoke all on table ai_request_log from anon, authenticated;

-- ---- Seed defaults (safe to re-run) --------------------------------------
insert into ai_provider_flags (provider_id, enabled, priority) values
  ('google', true, 1), ('openai', true, 2), ('anthropic', true, 3)
on conflict (provider_id) do nothing;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ai_reports.sql

-- SmartBudget — reports on AI assistant answers ("Report this answer").
--
-- Google Play requires apps with generative AI to let users flag offensive
-- or wrong output. Users can only insert their own reports; the owner reviews
-- them in the Supabase dashboard (service role). Run once in the SQL editor.

create table if not exists public.ai_reports (
  id          bigint generated always as identity primary key,
  user_id     uuid not null default auth.uid()
              references auth.users(id) on delete cascade,
  reason      text not null check (reason in ('inaccurate', 'harmful', 'other')),
  answer      text not null check (char_length(answer) <= 8000),
  note        text check (char_length(note) <= 1000),
  created_at  timestamptz not null default now()
);

alter table public.ai_reports enable row level security;

drop policy if exists "ai_reports_insert_own" on public.ai_reports;
create policy "ai_reports_insert_own" on public.ai_reports
  for insert to authenticated
  with check (user_id = auth.uid());

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> receipt_scanner.sql

-- ============================================================================
-- SmartBudget — Receipt Scanner: remove personal (BYOK) Gemini keys
-- ----------------------------------------------------------------------------
-- DGOTIX is the only AI provider: receipt scanning uses the server's own key
-- (GEMINI_API_KEY Edge Function secret) and every scan is metered against the
-- plan's cloud-OCR quota. Users no longer store personal keys, so the old
-- encrypted-key table is removed along with any keys it held.
--
-- Apply via the Supabase SQL editor or CLI. Safe to re-run.
-- ============================================================================

drop table if exists user_ai_keys;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> security_hardening.sql

-- ============================================================================
-- SmartBudget — security hardening (run after the other files; safe to re-run)
-- ----------------------------------------------------------------------------
-- 1. Usage is reserved atomically before a model is called, so parallel
--    requests can't all pass the quota check, and a platform-wide monthly
--    ceiling caps total AI and cloud-OCR spend.
-- 2. Payment webhooks remember the time of the last event applied, so an
--    older event arriving late can't undo a newer one.
-- 3. Clients can't set the (unused) plan column on their own profile.
-- 4. A cloud backup can't exceed 10 MB.
-- Until this file is run, the Edge Functions keep working as before.
-- ============================================================================

-- ---- 1. Atomic usage reservation -------------------------------------------
create index if not exists ai_usage_monthly_month_idx on ai_usage_monthly(month);
create index if not exists ocr_usage_monthly_month_idx on ocr_usage_monthly(month);

-- Counts one AI request ('ai') or cloud scan ('ocr') for the user, unless the
-- user's limit (lifetime or this month) or the platform-wide monthly limit
-- (null = none) is reached. Returns 'ok', 'quota' or 'global'.
create or replace function public.reserve_usage(
  p_user uuid,
  p_kind text,
  p_month text,
  p_limit int,
  p_lifetime boolean,
  p_global_limit int
) returns text
language plpgsql security definer set search_path = public as $$
declare
  used  int;
  total bigint;
begin
  if p_kind not in ('ai', 'ocr') then
    raise exception 'unknown usage kind %', p_kind;
  end if;
  -- One reservation at a time per user and kind: parallel requests queue here.
  perform pg_advisory_xact_lock(hashtextextended(p_kind || ':' || p_user::text, 0));

  if p_kind = 'ai' then
    if p_lifetime then
      select requests into used from ai_usage_lifetime where user_id = p_user;
    else
      select requests into used from ai_usage_monthly
        where user_id = p_user and month = p_month;
    end if;
  else
    if p_lifetime then
      select scans into used from ocr_usage_lifetime where user_id = p_user;
    else
      select scans into used from ocr_usage_monthly
        where user_id = p_user and month = p_month;
    end if;
  end if;
  if coalesce(used, 0) >= p_limit then
    return 'quota';
  end if;

  if p_global_limit is not null then
    if p_kind = 'ai' then
      select coalesce(sum(requests), 0) into total from ai_usage_monthly
        where month = p_month;
    else
      select coalesce(sum(scans), 0) into total from ocr_usage_monthly
        where month = p_month;
    end if;
    if total >= p_global_limit then
      return 'global';
    end if;
  end if;

  if p_kind = 'ai' then
    insert into ai_usage_monthly as u (user_id, month, requests)
      values (p_user, p_month, 1)
      on conflict (user_id, month)
      do update set requests = u.requests + 1, updated_at = now();
    insert into ai_usage_lifetime as u (user_id, requests)
      values (p_user, 1)
      on conflict (user_id)
      do update set requests = u.requests + 1, updated_at = now();
  else
    insert into ocr_usage_monthly as u (user_id, month, scans)
      values (p_user, p_month, 1)
      on conflict (user_id, month)
      do update set scans = u.scans + 1, updated_at = now();
    insert into ocr_usage_lifetime as u (user_id, scans)
      values (p_user, 1)
      on conflict (user_id)
      do update set scans = u.scans + 1, updated_at = now();
  end if;
  return 'ok';
end $$;

-- Gives back a reservation whose request then failed (never below zero).
create or replace function public.release_usage(
  p_user uuid,
  p_kind text,
  p_month text
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if p_kind = 'ai' then
    update ai_usage_monthly set requests = greatest(requests - 1, 0), updated_at = now()
      where user_id = p_user and month = p_month;
    update ai_usage_lifetime set requests = greatest(requests - 1, 0), updated_at = now()
      where user_id = p_user;
  elsif p_kind = 'ocr' then
    update ocr_usage_monthly set scans = greatest(scans - 1, 0), updated_at = now()
      where user_id = p_user and month = p_month;
    update ocr_usage_lifetime set scans = greatest(scans - 1, 0), updated_at = now()
      where user_id = p_user;
  end if;
end $$;

-- Only the Edge Functions (service role) may call them.
revoke all on function public.reserve_usage(uuid, text, text, int, boolean, int)
  from public, anon, authenticated;
revoke all on function public.release_usage(uuid, text, text)
  from public, anon, authenticated;
grant execute on function public.reserve_usage(uuid, text, text, int, boolean, int)
  to service_role;
grant execute on function public.release_usage(uuid, text, text)
  to service_role;

-- ---- 2. Webhook event ordering ---------------------------------------------
alter table subscriptions add column if not exists provider_event_at timestamptz;

-- ---- 3. Profile plan is server-only ----------------------------------------
-- Rows are created by the signup trigger; the user may change only these.
revoke insert, update on table profiles from anon, authenticated;
grant update (display_name, locale, theme, base_currency, updated_at)
  on table profiles to authenticated;

-- ---- 4. Backup size ---------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'user_backups_size'
  ) then
    alter table public.user_backups
      add constraint user_backups_size
      check (pg_column_size(data) <= 10485760) not valid;
  end if;
end $$;

commit;
