#!/usr/bin/env bash
# Rebuilds supabase/setup_all.sql: every SQL file in the order they must run,
# as one transaction, so a new Supabase project is set up with a single paste
# in the SQL editor. Run after editing any of the files listed below.
set -euo pipefail
cd "$(dirname "$0")/../supabase"
files=(schema.sql cloud_backup.sql billing.sql coupons.sql ai_gateway.sql
       ai_reports.sql receipt_scanner.sql security_hardening.sql
       subscription_lifecycle.sql)
{
  echo "-- ============================================================================"
  echo "-- SmartBudget: full database setup in one paste (Supabase SQL editor)."
  echo "-- Generated by tool/build_supabase_setup.sh from, in this order:"
  echo "--   ${files[*]}"
  echo "-- Edit those files, not this one. Runs as one transaction (all or"
  echo "-- nothing) and is safe to run again."
  echo "-- ============================================================================"
  echo
  echo "begin;"
  for f in "${files[@]}"; do
    printf '\n-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> %s\n\n' "$f"
    cat "$f"
  done
  printf '\ncommit;\n'
} > setup_all.sql
